# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  lint:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict

  format:
    runs-on: macos-15
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Run SwiftFormat
        run: swiftformat .
      - name: Commit changes if needed
        uses: ryohidaka/action-commit-push@v0.6.0
        with:
          commit-message: "chore: コード整形"
          rebase: true
          force-push: true

  build:
    runs-on: macos-15
    needs: format
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
      - run: swift build -v

  tests:
    runs-on: macos-15
    needs: format
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
      - run: swift test -v
